<?php
$_element = $this->getElement();
$this->setFieldName($_element->getName());
$fValue = $_element->getValue();
/** @var \Unirgy\Dropship\Helper\Data $_hlp */
$_hlp = \Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\Dropship\Helper\Data');
if (!is_array($fValue)) {
    $fValue = $_hlp->unserializeArr($fValue);
}
?>

<div class="grid control">
    <input id="<?php echo $this->getFieldName()?>" type="hidden" />
    <table cellspacing="0" class="data admin__control-table" id="<?php echo $this->suffixId('cfgTable')?>" style="width:850px">
        <col width="300" />
        <col width="300" />
        <col width="150" />
        <col width="100" />
        <thead>
        <tr class="headings">
            <th><?php echo __('Template') ?></th>
            <th><?php echo __('Item Separate Template') ?></th>
            <th><?php echo __('Totals Template') ?></th>
            <th><?php echo __('Action') ?></th>
        </tr>
        <tr id="<?php echo $this->suffixId('rowTpl')?>" style="display:none">
            <td>
                <h2><?php echo __('Title')?></h2>
                <input type="text" class="input-text" name="<?php echo $this->getFieldName()?>[$ROW][title]" value="$TITLE" style="width:150px" />
                <h2><?php echo __('Sort Order')?></h2>
                <input type="text" class="input-text" name="<?php echo $this->getFieldName()?>[$ROW][sort_order]" value="$SORT_ORDER" style="width:80px" />
                <h2><?php echo __('Template') ?></h2>
                <textarea name="<?php echo $this->getFieldName()?>[$ROW][template]" style="width:200px">$TEMPLATE</textarea>
                <h2><?php echo __('Header') ?></h2>
                <textarea name="<?php echo $this->getFieldName()?>[$ROW][header]" style="width:200px">$HEADER</textarea>
            </td>
            <td>
                <label><?php echo __('Use Item Separate Template')?></label><br />
                <select name="<?php echo $this->getFieldName()?>[$ROW][use_item_template]" style="width:100px">
                    <option alt="use_item_template" value="0"><?php echo __('No')?></option>
                    <option alt="use_item_template" value="1"><?php echo __('Yes')?></option>
                </select>
                <br />
                <label><?php echo __('Item Separate Template')?></label><br />
                <textarea name="<?php echo $this->getFieldName()?>[$ROW][item_template]" style="width:200px">$ITEM_TEMPLATE</textarea>
                <br />
                <label><?php echo __('Footer Separate Template')?></label><br />
                <textarea name="<?php echo $this->getFieldName()?>[$ROW][footer_template]" style="width:200px">$FOOTER_TEMPLATE</textarea>
            </td>
            <td>
                <textarea name="<?php echo $this->getFieldName()?>[$ROW][totals_template]" style="width:200px">$TOTALS_TEMPLATE</textarea>
            </td>
            <td>
                <button type="button" class="scalable delete delete-fieldset"><span><?php echo __('Remove') ?></span></button>
            </td>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <th colspan="4" class="a-left">
                <div class="left"><button type="button" class="scalable add" id="<?php echo $this->suffixId('addBtn')?>"><span>+ <?php echo __('Add Template') ?></span></button></div>
            </th>
        </tr>
        </tfoot>
        <tbody class="<?php echo $this->suffixId('body')?>">
        </tbody>
    </table>

</div>

<style type="text/css">
</style>

<script type="text/javascript">
require(["jquery", "prototype"], function(jQuery) {

    //<![CDATA[
    (function ()
    {
        var lastRowNum = 0;
        var tbody = $$('#<?php echo $this->suffixId('cfgTable')?> tbody.<?php echo $this->suffixId('body')?>')[0]

        function addRow(inData)
        {
            var rowHtml = $('<?php echo $this->suffixId('rowTpl')?>').innerHTML
            var data = {
                title: '',
                template: '',
                header: '',
                use_item_template: 0,
                item_template: '',
                footer_template: '',
                totals_template: '',
                sort_order: '0'
            }
            Object.extend(data, inData);
            data.row = ++lastRowNum;

            var isIE = (/msie [1-8]\./i).test(navigator.userAgent);
            var numericVars = ['sort_order', 'use_item_template'];
            var forcedNumericVars = [];
            var keys = $H(data).keys().sortBy(function(s){return (''+s).length}).reverse();
            for (j=0; j<keys.length; j++) {
                var i=keys[j];
                value = data[i] || ''
                if (-1 != numericVars.indexOf(i) && data[i]
                    || -1 != forcedNumericVars.indexOf(i)
                    ) {
                    value *= 1;
                    data[i] = value;
                }
                if (i!=='row' && isIE) value = '"'+value+'"';
                rowHtml = rowHtml.replace(new RegExp('\\$'+i.toUpperCase(), 'g'), value)
            }
            var regExTpl = [
                new Template('<option (([^>]*(alt="?#{key}"?|value="?#{value}"?(?=[\\s>]))){2})'),
                new Template('<option $1 selected="selected"'),
                new Template('<input (([^>]*(alt="?#{key}"?|value="?#{value}"?(?=[\\s>])|type="?checkbox"?)){3})'),
                new Template('<input $1 checked="checked"')
            ];
            var selectFields = $H({sort_order:0,use_item_template:0});
            selectFields.each(function(pair){
                var varsForEval, value=data[pair.key], key=pair.key;
                for (var rxIdx=0; rxIdx<regExTpl.length; rxIdx+=2) {
                    varsForEval = [];
                    if (pair.value) {
                        if (!Object.isArray(value)) {
                            value = String.interpret(value).split(',');
                        }
                        value.each(function(val){
                            varsForEval.push({key: RegExp.escape(key), value: RegExp.escape(val)});
                        })
                    } else {
                        varsForEval.push({key: RegExp.escape(key), value: RegExp.escape(value)});
                    }
                    for (var vfeIdx=0; vfeIdx<varsForEval.length; vfeIdx++) {
                        var varForEval = varsForEval[vfeIdx];
                        var rxFind = regExTpl[rxIdx].evaluate(varForEval);
                        var rxReplace = regExTpl[rxIdx+1].evaluate(varForEval);
                        rowHtml = rowHtml.replace(new RegExp(rxFind, 'i'), rxReplace);
                    }
                }
            });
            tbody.insert('<tr>'+rowHtml+'</tr>')
            var trs = tbody.childElements()
            var tr = trs[trs.length-1]
            tr.addClassName(lastRowNum%2 ? 'odd' : 'even')
            var del = $(tr).select('button.delete-fieldset')[0];
            if (del) {
                $(del).observe('click', function(e) { e.stop(); $(del.parentNode.parentNode).remove() })
            }
        }

        $('<?php echo $this->suffixId('addBtn')?>').observe('click', function(e) { e.stop(); addRow() });

        <?php if (is_array($fValue)): foreach ($fValue as $fV): ?>
        addRow(<?php echo \Zend\Json\Json::encode($fV) ?>);
        <?php endforeach; endif; ?>
    })();
    //]]>

});
</script>