<?php
/** @var \Unirgy\Dropship\Helper\Data $_hlp */
$_hlp = \Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\Dropship\Helper\Data');
$_v = $this->getVendor();
$useUdTitles = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\App\Config\ScopeConfigInterface')->isSetFlag('carriers/udsplit/use_dropship_titles', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
?>

<?php switch ($this->getPart()): case 'header': ?>

<tr class="udropship-cart-vendor-header">
    <td colspan="10" style="padding-top:5px; padding-bottom:0">
    <?php if ($_v->getId()): ?>
        <h3><?php echo $_v->getVendorName() ?> - <?php echo $_v->getFormatedAddress('text_small') ?></h3>
    <?php else: ?>
        <h3>Unknown vendor</h3>
    <?php endif ?>
    <?php $vendorErrors = $this->getQuote1()->getMinVendorOrderAmountErrors(); ?>
    <?php if (!empty($vendorErrors) && !empty($vendorErrors[$_v->getId()])): ?>
        <p class="item-msg error">* <?php echo $this->escapeHtml($vendorErrors[$_v->getId()]) ?></p>
    <?php endif ?>
    </td>
</tr>

<?php break; case 'footer': ?>

<tr class="udropship-cart-vendor-footer">
    <td colspan="10">
        <div style="float:right">
            <?php echo __('Subtotal:')?>
            <strong><?php echo $_hlp->formatPrice($this->getSubtotal()) ?></strong>
        </div>
        <?php if (0&&!$this->isVirtual()): ?>
        <?php if ($this->getErrorsOnly()): ?>
            <?php echo htmlspecialchars(\Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('carriers/udsplit/specificerrmsg', \Magento\Store\Model\ScopeInterface::SCOPE_STORE)) ?>
        <?php else: ?>
        <?php if (($_shippingRateGroups = $this->getEstimateRates())): ?>
        <?php echo __('Select Shipping:')?>
        <select name="cart[estimate_method][<?php echo $_v->getId()?>]" class="shipment-methods" style="width:auto">
        <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
            <?php if (!$useUdTitles):?>
                <optgroup label="<?php echo $this->getCarrierName($code) ?>">
            <?php endif ?>
            <?php foreach ($_rates as $_rate): ?>
            <?php if ($_rate->getErrorMessage()): ?>
                <?php //echo $_rate->getErrorMessage() ?>
            <?php else:
                $_price = $this->getShippingPrice($_rate->getPrice(), \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Tax\Helper\Data')->displayShippingPriceIncludingTax());
                $_incl = $this->getShippingPrice($_rate->getPrice(), true);
                if (\Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Tax\Helper\Data')->displayShippingBothPrices() && $_incl != $_price) {
                    $_price .= ' ('.__('Incl. Tax ').$_incl.')';
                }
            ?>
                <option value="<?php echo $this->escapeHtml($_rate->getCode()) ?>" <?php if($_rate->getCode()===$this->getShippingMethod('code')) echo ' selected="selected"' ?>>
                    <?php echo $_rate->getMethodTitle() ?> - <?php echo $_price ?>
                </option>
            <?php endif ?>
            <?php endforeach; ?>
            <?php if (!$useUdTitles):?>
                </optgroup>
            <?php endif ?>
        <?php endforeach; ?>
        </select>
        <?php endif; ?>
        <?php endif; ?>
        <?php endif; ?>
    </td>
</tr>

<?php endswitch ?>
