<div class="admin__table-wrapper">
    <table class="data-table admin__table-primary order-shipment-table">
        <thead>
        <tr class="headings">
                <th><?php echo __('Product') ?></th>
                <th class="a-center"><?php echo __('Condition') ?></th>
                <th class="a-center last"><span class="nobr"><?php echo __('Qty') ?></span></th>
            </tr>
        </thead>
        <?php $_items = $this->getRma()->getAllItems() ?>
        <?php $_i=0;foreach ($_items as $_item): if ($_item->getOrderItem()->getIsVirtual() || $_item->getOrderItem()->getParentItem()): continue; endif; $_i++ ?>
            <tbody class="<?php echo $_i%2?'odd':'even' ?>">
                <?php echo $this->getItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
</div>
