<?php
/** @var Unirgy\DropshipTierCommission\Block\Adminhtml\SystemConfigField\Rates $block */
/** @var Magento\Framework\Data\Form\Element\AbstractElement $_element */
?>

<?php
$_tsHlp = $block->getHelper();
$_htmlId = $block->getHtmlId() ? $block->getHtmlId() : '_' . uniqid();
$_element = $block->getElement()
?>
<div class="grid control">
    <table cellspacing="0" class="data admin__control-table" cellpadding="0" id="global_tiercom_category_rates-grid" style="width: 650px">
        <col width="150">
        <col width="120">
        <thead>
        <tr class="headings">
            <th class="a-center"><?php echo __('Category') ?></th>
            <th class="a-center"><?php echo __('Default Commission Percent (per item)') ?></th>
            <th class="a-center"><?php echo __('Default Fixed Rate (per item)') ?></th>
        </tr>
        </thead>
        <tbody id="global_tiercom_category_rates-table">
        <?php $_globalTSC = $_element->getValue(); ?>
        <?php $i = 0;
        foreach ($block->getTopCategories() as $_topCat): ?>
            <?php $_catId = $_topCat->getId(); ?>
            <tr class="option-row">
                <td class="a-left"><?php echo $_topCat->getName() ?></td>
                <td class="a-center"><input name="<?php echo $_element->getName() ?>[<?php echo $_catId ?>][value]"
                                            class="input-text" type="text"
                                            value="<?php echo @$_globalTSC[$_catId]['value'] ?>"/></td>
                <td class="a-center"><input name="<?php echo $_element->getName() ?>[<?php echo $_catId ?>][fixed]"
                                            class="input-text" type="text"
                                            value="<?php echo @$_globalTSC[$_catId]['fixed'] ?>"/></td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</div>

<style type="text/css">
    #global_tiercom_category_rates-table input {
        width: 80px
    }
</style>
