<?php
$filterManager = \Magento\Framework\App\ObjectManager::getInstance()->get('\Magento\Framework\Filter\FilterManager');
$qaHlp = \Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\DropshipVendorAskQuestion\Helper\Data');
?>
<?php $_questions = $this->getQuestionsCollection(); ?>
<?php if($_questions->getSize()): ?>
<h2><?php echo __('Vendor Questions/Answers') ?></h2>
<?php echo $this->getChildHtml('toolbar') ?>
<dl id="questions-list">
    <?php foreach ($_questions as $_question): ?>
    <dt><?php echo __('<b>%1</b> asks vendor <b>%2</b>', $_question->getCustomerName(), $_question->getVendorName())?> </dt>
    <dd>
        <h5><?php echo __('Question Text')?></h5>
        <p><?php echo $this->escapeHtml($_question->getQuestionText()); ?></p>
        <?php if ($_question->getAnswerText()): ?>
        <h5><?php echo __('Answer')?></h5>
        <p><?php echo $this->escapeHtml($_question->getAnswerText()); ?></p>
        <?php else: ?>
        <p><?php echo __('Not Answered yet')?></p>
        <?php endif ?>
    </dd>
    <?php endforeach; ?>
</dl>
<script type="text/javascript">
require(["jquery", "prototype"], function(jQuery) {
decorateDataList('questions-list');
});
</script>
<?php echo $this->getChildHtml('toolbar') ?>
<?php else: ?>
<p><?php echo __('No questions asked yet.'); ?></p>
<?php endif ?>
