<?php
    $_hlp = \Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\DropshipSellYours\Helper\Data');
    $_udHlp = \Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\Dropship\Helper\Data');
    $_helper = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Catalog\Helper\Output');
    $_product = $this->getParentBlock()->getProduct();
    $_mvData = new \Magento\Framework\DataObject(\Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\Registry')->registry('sell_yours_data_'.$_product->getId()));
    $_pId = $_product->getId();
?>
    <form id="udsell-sell-<?php echo $_pId?>" method="post" action="<?php echo $this->getUrl('udsell/index/sellPost', ['id'=>$_product->getId()])?>">
    	<div class="product-sell-option">
			<h3><?php echo __('Sell Yours') ?></h3>
    		<div class="row-options-container">
		        <div class="form-add">
		            <ul class="form-list">
		            <li>
		            <div class="fields">
		                <div class="field">
		                    <label for="vendor_price-<?php echo $_pId?>"><?php echo __('Price') ?> <span class="required">*</span> </label><br />
		                    <input name="vendor_price" value="<?php echo $_hlp->processFormVar($_mvData->getVendorPrice(), 1)?>" title="<?php echo __('Price') ?>" id="vendor_price-<?php echo $_pId?>" type="text" class="input-text required-entry" />
		                </div>
		                <div class="field">
		                    <label for="stock_qty-<?php echo $_pId?>"><?php echo __('Stock Qty') ?></small> <span class="required">*</span></label><br />
		                    <input name="stock_qty" value="<?php echo $_hlp->processFormVar($_mvData->getStockQty(), 1)?>" title="<?php echo __('Stock Qty') ?>" id="stock_qty-<?php echo $_pId?>" type="text" class="input-text required-entry validate-number" />
		                </div>
		            </div>
		            </li>
		            <li>
		            <div class="fields">
		                <div class="field">
		                <label for="state-<?php echo $_pId?>"><?php echo __('State/Condition') ?> </label><br />
		                <?php echo $block->getLayout()->createBlock('Magento\Framework\Block\Html\Select')
		                        ->setName('state')
		                        ->setId("state-{$_pId}")
		                        ->setTitle(__('State/Condition'))
		                        ->setValue($_mvData->getState())
		                        ->setOptions(\Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\DropshipMultiPrice\Model\Source')->setPath('vendor_product_state')->toOptionArray())
		                        ->getHtml();
		                ?>
		                </div>
		                <div class="field">
		                    <label for="state_descr-<?php echo $_pId?>"><?php echo __('State Description') ?> </label><br />
		                    <input name="state_descr" value="<?php echo $_mvData->getStateDescr()?>" title="<?php echo __('State Description') ?>" id="state_descr-<?php echo $_pId?>" type="text" class="input-text" />
		                </div>
		            </div>
		            </li>
		            <li>
		            <div class="fields">
                        <?php /*
		                <div class="field">
		                    <label for="vendor_sku-<?php echo $_pId?>"><?php echo __('My SKU') ?> </label><br />
		                    <input name="vendor_sku" value="<?php echo $_mvData->getVendorSku()?>" title="<?php echo __('My SKU') ?>" id="vendor_sku-<?php echo $_pId?>" type="text" class="input-text" />
		                </div>
                        */?>
                        <div class="field">
		                    <?php if (\Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\DropshipMulti\Helper\Data')->isVendorProductShipping()): ?>
		                    <label for="shipping_price-<?php echo $_pId?>"><?php echo __('Shipping Price') ?> </label><br />
		                    <input name="shipping_price" value="<?php echo $_mvData->getShippingPrice()*1?>" title="<?php echo __('Shipping Price') ?>" id="shipping_price-<?php echo $_pId?>" type="text" class="input-text" />
		                    <?php endif ?>
		                </div>
		                <div class="field">
		                    <label for="vendor_title-<?php echo $_pId?>"><?php echo __('My Title') ?> </label><br />
		                    <textarea name="vendor_title" title="<?php echo __('My Title') ?>" id="vendor_title-<?php echo $_pId?>" type="text" class="input-text"><?php echo $this->escapeHtml($_mvData->getVendorTitle())?></textarea>
		                </div>
		            </li>
                        <?php /*
		            <?php if (\Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\DropshipMulti\Helper\Data')->isVendorProductShipping()): ?>
		            <li>
		            <div class="fields">
		                <div class="field">
		                    <?php if (\Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\DropshipMulti\Helper\Data')->isVendorProductShipping()): ?>
		                    <label for="shipping_price-<?php echo $_pId?>"><?php echo __('Shipping Price') ?> </label><br />
		                    <input name="shipping_price" value="<?php echo $_mvData->getShippingPrice()*1?>" title="<?php echo __('Shipping Price') ?>" id="shipping_price-<?php echo $_pId?>" type="text" class="input-text" />
		                    <?php endif ?>
		                </div>
		            </li>
		            <?php endif ?>
                        */?>
		            </ul>
		        </div>
	        </div>
		</div>
	        <div class="buttons-set">
	            <button type="submit" title="<?php echo __('Submit') ?>" class="button"><span><?php echo __('Submit') ?></span></button>
	            <p class="required"><?php echo __('* Required Fields') ?></p>
	        </div>
    </form>

    <script type="text/javascript">
    //<![CDATA[
        
require(["jquery", "prototype", 'varien/form'], function(jQuery) {
var dataForm = new VarienForm('udsell-sell-<?php echo $_pId?>', true);
});

    //]]>
    </script>