<?php $_item = $this->getItem() ?>
<tr>
    <td align="left" valign="top" style="font-size:11px; padding:3px 9px;">
        <strong><?php echo $this->escapeHtml($_item->getName()) ?></strong>
        <?php if ($this->getItemOptions()): ?>
        <dl style="margin:0; padding:0;">
            <?php foreach ($this->getItemOptions() as $option): ?>
            <dt><strong><em><?php echo $option['label'] ?></em></strong></dt>
            <dd style="margin:0; padding:0 0 0 9px;"><?php echo $option['value'] ?></dd>
            <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?php echo $this->escapeHtml($_item->getDescription()) ?>
    </td>
    <td align="left" valign="top" style="font-size:11px; padding:3px 9px;"><?php echo $this->escapeHtml($this->getSku($_item)) ?></td>
    <td align="left" valign="top" style="font-size:11px; padding:3px 9px;"><?php echo $this->escapeHtml($_item->getItemConditionName()) ?></td>
    <td align="center" valign="top" style="font-size:11px; padding:3px 9px;"><?php echo $_item->getQty()*1 ?></td>
</tr>
