<?php
$_tsHlp = \Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\DropshipTierShipping\Helper\Data');
$_htmlId = $this->getHtmlId() ? $this->getHtmlId() : '_' . uniqid();
$_element = $this->getElement();
$cShipClass = \Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\DropshipShippingClass\Model\Source')->setPath('customer_ship_class')->toOptionHash();
$rateBlock = $this->getLayout()->createBlock('Unirgy\DropshipTierShipping\Block\Adminhtml\SystemConfigField\SimpleRateSingle');
$__value = is_array($_element->getValue()) ? $_element->getValue() : [];
$rateBlock->setBaseName($_element->getName())->setDataObject(new \Magento\Framework\DataObject($__value));

$subkeyColumns = [
    'cost' => 'cost',
    'additional' => 'additional'
];

$tableWidth = '650px';


?>
<div class="grid control">
    <table cellspacing="0" class="data admin__control-table" cellpadding="0" id="global_tiership_simple_rates-grid" style="width: <?php echo $tableWidth?>">
        <col width="150">
        <?php for ($i=0; $i<count($subkeyColumns); $i+=2): ?>
        <col width="120">
        <?php endfor ?>
        <thead>
        <tr class="headings">
            <th class="a-center"><?php echo __('Customer') ?></th>
            <?php for ($i=0; $i<count($subkeyColumns); $i++): ?>
            <th class="a-center"><?php echo $this->getColumnTitle($subkeyColumns, $i) ?></th>
            <?php endfor ?>
        </tr>
        </thead>
        <tbody id="global_tiership_simple_rates-table">

            <?php foreach($cShipClass as $cscId => $cscLabel): ?>

            <tr class="option-row">

                <td class="a-left"><?php echo $cscLabel?></td>
                <?php $rateBlock->setKey($cscId);  ?>

                <?php foreach ($subkeyColumns as $subKey=>$subKeyType): ?>
                <td class="a-center"><?php echo $rateBlock->setSubkey($subKey)->setSubkeyType($subKeyType)->toHtml() ?></td>
                <?php endforeach ?>

            </tr>

            <?php endforeach ?>

        </tbody>
    </table>
</div>

<style type="text/css">
    #global_tiership_category_rates-table input {width: 80px}
</style>
