<?php
$_element = $this->getElement();
$this->setFieldName($_element->getName());
$fValue = $_element->getValue();
/** @var \Unirgy\Dropship\Helper\Data $_hlp */
$_hlp = \Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\Dropship\Helper\Data');
if (!is_array($fValue)) {
    $fValue = $_hlp->unserializeArr($fValue);
}
?>

<div class="grid control">
    <input id="<?php echo $this->getFieldName()?>" type="hidden" />
    <table cellspacing="0" class="data admin__control-table" id="<?php echo $this->suffixId('cfgTable')?>" style="width:70px">
        <col width="100" />
        <col width="150" />
        <col width="100" />
        <col width="100" />
        <col width="100" />
        <col width="100" />
        <thead>
        <tr class="headings">
            <th><?php echo __('General') ?></th>
            <th><?php echo __('Billing') ?></th>
            <th><?php echo __('Limits') ?></th>
            <th><?php echo __('Sort Order') ?></th>
            <th><?php echo __('Action') ?></th>
        </tr>
        <tr id="<?php echo $this->suffixId('rowTpl')?>" style="display:none">
            <td>
                <label><b><?php echo __('Code:') ?></b></label><br />
                <input type="text" class="input-text" name="<?php echo $this->getFieldName()?>[$ROW][membership_code]" value="$MEMBERSHIP_CODE" style="width:100px" />
                <br />
                <label><b><?php echo __('Title:') ?></b></label><br />
                <input type="text" class="input-text" name="<?php echo $this->getFieldName()?>[$ROW][membership_title]" value="$MEMBERSHIP_TITLE" style="width:150px" />
                <input type="hidden" name="<?php echo $this->getFieldName()?>[$ROW][membership_id]" value="$MEMBERSHIP_ID" />
            </td>
            <td>
                <nobr>
                <label><?php echo __('Billing Type:') ?></label>
                <select name="<?php echo $this->getFieldName()?>[$ROW][billing_type]" onchange="udmemberToggle($H({billing_type: ['paypal','offline']}), {billing_type: this.value}, $ROW)" style="width: 150px">
                    <option alt="billing_type" value="offline"><?php echo __('Offline (Manual)')?></option>
                    <!--option alt="billing_type" value="paypal"><?php echo __('Auto (Paypal Express)')?></option-->
                </select>
                </nobr>
                <br />
                <div class="<?php echo 'yes__billing_type_paypal_$ROW' ?>">
                <label><?php echo __('Product SKU:') ?></label><br />
                <input type="text" class="input-text" name="<?php echo $this->getFieldName()?>[$ROW][membership_sku]" value="$MEMBERSHIP_SKU" style="width:200px" />
                </div>
            </td>
            <td>
                <nobr>
                    <label><?php echo __('Limit Products:') ?></label>
                    <input type="text" class="input-text" name="<?php echo $this->getFieldName()?>[$ROW][limit_products]" value="$LIMIT_PRODUCTS" style="width:100px" />
                </nobr>
                <br />
                <nobr>
                    <label><?php echo __('Allow Microsite:') ?></label>
                    <select name="<?php echo $this->getFieldName()?>[$ROW][allow_microsite]" style="width: 80px">
                        <option alt="allow_microsite" value="1"><?php echo __('Yes')?></option>
                        <option alt="allow_microsite" value="0"><?php echo __('No')?></option>
                    </select>
                </nobr>
                <br />
                <nobr>
                    <label><?php echo __('Show On Registration Form:') ?></label>
                    <select name="<?php echo $this->getFieldName()?>[$ROW][allow_registration]" style="width: 80px">
                        <option alt="allow_registration" value="1"><?php echo __('Yes')?></option>
                        <option alt="allow_registration" value="0"><?php echo __('No')?></option>
                    </select>
                </nobr>
            </td>
            <td>
                <input type="text" class="input-text" name="<?php echo $this->getFieldName()?>[$ROW][sort_order]" value="$SORT_ORDER" style="width:100px" />
            </td>
            <td>
                <button type="button" class="scalable delete delete-fieldset"><span><?php echo __('Remove') ?></span></button>
            </td>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <th colspan="5" class="a-left">
                <div class="left"><button type="button" class="scalable add" id="<?php echo $this->suffixId('addBtn')?>"><span>+ <?php echo __('Add Membership Type') ?></span></button></div>
            </th>
        </tr>
        </tfoot>
        <tbody class="<?php echo $this->suffixId('body')?>">
        </tbody>
    </table>

</div>

<style type="text/css">
</style>

<script type="text/javascript">
    //<![CDATA[
    
require(["jquery", "prototype"], function(jQuery) {
    var suffixIdTpl = new Template('<?php echo '#{key}' ?>');
    window.udmemberToggle = function (toggleFields, data, row)
    {
        toggleFields.each(function(pair) {
            var key = pair.key
            console.log(pair)
            $A(pair.value).each(function(val) {
                var yesKey = suffixIdTpl.evaluate({key: 'yes__'+key+'_'+val+'_'+row});
                var noKey = suffixIdTpl.evaluate({key: 'no__'+key+'_'+val+'_'+row});
                console.log(val)
                console.log(data[key])
                if (data[key]!=val) {
                    $$('.'+yesKey).invoke('hide');
                    $$('.'+noKey).invoke('show');
                } else {
                    $$('.'+yesKey).invoke('show');
                    $$('.'+noKey).invoke('hide');
                }
            })
        });
    }
    var lastRowNum = 0;
    var tbody = $$('#<?php echo $this->suffixId('cfgTable')?> tbody.<?php echo $this->suffixId('body')?>')[0]

    function addRow(inData)
    {
        var rowHtml = $('<?php echo $this->suffixId('rowTpl')?>').innerHTML
        var data = {
            membership_id: 0,
            membership_title: '',
            membership_code: '',
            membership_sku: '',
            billing_type: 'offline',
            allow_microsite: 1,
            allow_registration: 1,
            limit_products: '',
            sort_order: '0'
        }
        Object.extend(data, inData);
        data.row = ++lastRowNum;

        var isIE = (/msie [1-8]\./i).test(navigator.userAgent);
        var numericVars = ['sort_order', 'membership_id', 'limit_products'];
        var forcedNumericVars = [];
        var keys = $H(data).keys().sortBy(function(s){return (''+s).length}).reverse();
        for (j=0; j<keys.length; j++) {
            var i=keys[j];
            value = data[i] || ''
            if (-1 != numericVars.indexOf(i) && data[i]
                || -1 != forcedNumericVars.indexOf(i)
                ) {
                value *= 1;
                data[i] = value;
            }
            if (i!=='row' && isIE) value = '"'+value+'"';
            rowHtml = rowHtml.replace(new RegExp('\\$'+i.toUpperCase(), 'g'), value)
        }
        var regExTpl = [
            new Template('<option (([^>]*(alt="?#{key}"?|value="?#{value}"?(?=[\\s>]))){2})'),
            new Template('<option $1 selected="selected"'),
            new Template('<input (([^>]*(alt="?#{key}"?|value="?#{value}"?(?=[\\s>])|type="?checkbox"?)){3})'),
            new Template('<input $1 checked="checked"')
        ];
        var selectFields = $H({billing_type: 0, allow_microsite: 0, allow_registration: 0});
        selectFields.each(function(pair){
            var varsForEval, value=data[pair.key], key=pair.key;
            for (var rxIdx=0; rxIdx<regExTpl.length; rxIdx+=2) {
                varsForEval = [];
                if (value) {
                    if (!Object.isArray(value)) {
                        value = String.interpret(value).split(',');
                    }
                    value.each(function(val){
                        varsForEval.push({key: key, value: val});
                    })
                } else {
                    varsForEval.push({key: key, value: value});
                }
                for (var vfeIdx=0; vfeIdx<varsForEval.length; vfeIdx++) {
                    var varForEval = varsForEval[vfeIdx];
                    var rxFind = regExTpl[rxIdx].evaluate(varForEval);
                    var rxReplace = regExTpl[rxIdx+1].evaluate(varForEval);
                    rowHtml = rowHtml.replace(new RegExp(rxFind, 'i'), rxReplace);
                }
            }
        });
        tbody.insert('<tr>'+rowHtml+'</tr>')
        var trs = tbody.childElements()
        var tr = trs[trs.length-1]
        tr.addClassName(lastRowNum%2 ? 'odd' : 'even')

        var toggleFields = $H({billing_type: ['paypal','offline']});
        udmemberToggle(toggleFields, data, data.row);

        var del = $(tr).select('button.delete-fieldset')[0];
        if (del) {
            $(del).observe('click', function(e) { e.stop(); $(del.parentNode.parentNode).remove() })
        }
    }

    $('<?php echo $this->suffixId('addBtn')?>').observe('click', function(e) { e.stop(); addRow() });

    <?php if (is_array($fValue)): foreach ($fValue as $fV): ?>
    addRow(<?php echo \Zend\Json\Json::encode($fV) ?>);
    <?php endforeach; endif; ?>
});

    //]]>
</script>