<?php
$_mHlp = \Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\DropshipMulti\Helper\Data');
$_yesnoOpts = \Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\Dropship\Model\Source')->setPath('yesno')->toOptionHash();
$store = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Store\Model\StoreManagerInterface')->getDefaultStoreView();
$customerGroupIds = $_mHlp->getCustomerGroups();
$websites = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Store\Model\StoreManagerInterface')->getWebsites(false);
?>

<div class="grid" style="width:400px">
    <input id="<?php echo $this->getFieldName()?>" type="hidden" />
    <table cellspacing="0" class="data" id="<?php echo $this->suffixId('cfgTable')?>" style="width:400px">
        <col />
        <col />
        <col width="50" />
        <col width="50" />
        <thead>
        <tr class="headings">
            <th><?php echo __('Website') ?></th>
            <th><?php echo __('Customer Group') ?></th>
            <th><?php echo __('Price') ?></th>
            <th><?php echo __('Action') ?></th>
        </tr>
        <tr id="<?php echo $this->suffixId('rowTpl')?>" style="display:none">
            <td>
                <select name="<?php echo $this->getFieldName()?>[$ROW][website_id]">
                    <option alt="website_id" value="0"><?php echo $this->escapeHtml(__('All Websites'))?></option>
                    <?php foreach ($websites as $website): ?>
                        <option alt="website_id" value="<?php echo $website->getId()?>"><?php echo $this->escapeHtml($website->getName())?></option>
                    <?php endforeach; ?>
                </select>
            </td>
            <td>
                <select name="<?php echo $this->getFieldName()?>[$ROW][customer_group_id]">
                    <?php foreach ($customerGroupIds as $cscId=>$cscLabel): ?>
                        <option alt="customer_group_id" value="<?php echo $cscId?>"><?php echo $this->escapeHtml($cscLabel)?></option>
                    <?php endforeach; ?>
                </select>
            </td>
            <td>
                <input type="text" class="input-text" name="<?php echo $this->getFieldName()?>[$ROW][value]" value="$VALUE" style="width:50px" />
                <input type="hidden" name="<?php echo $this->getFieldName()?>[$ROW][value_id]" value="$VALUE_ID" />
            </td>
            <td>
                <button type="button" class="scalable delete"><span></span></button>
            </td>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <th colspan="4" class="a-left">
                <div class="left"><button type="button" class="scalable add" id="<?php echo $this->suffixId('addBtn')?>"><span><?php echo __('Add Group Price') ?></span></button></div>
            </th>
        </tr>
        </tfoot>
        <tbody>
        </tbody>
    </table>

</div>

<style type="text/css">
</style>