<?php
/** @var \Unirgy\Dropship\Helper\Data $_hlp */
$_hlp = \Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\Dropship\Helper\Data');
$_v = $this->getVendor();
$_a = $this->getAddress();
$useUdTitles = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\App\Config\ScopeConfigInterface')->isSetFlag('carriers/udsplit/use_dropship_titles', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
?>
<?php switch ($this->getPart()): case 'header': ?>

<?php if (\Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\Dropship\Helper\Data')->compareMageVer('1.4.1.0', '1.8.0.0')): ?>
<tr>
    <td colspan="<?php if (\Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Tax\Helper\Data')->displayCartBothPrices()) {echo '6';} else {echo '4';}?>">
<?php endif ?>

<?php if ($_v->getId()): ?>
    <h4><?php echo $_v->getVendorName() ?> - <?php echo $_v->getCity().', '.$_v->getRegionCode() ?></h4>
<?php else: ?>
    <h4><?php echo __('Unknown vendor')?></h4>
<?php endif ?>

<?php if (\Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\Dropship\Helper\Data')->compareMageVer('1.4.1.0', '1.8.0.0')): ?>
</td></tr>
<?php endif ?>

<?php break; case 'footer':

$_shippingRateGroups = $this->getEstimateRates();
$_error = false;
foreach ($_shippingRateGroups as $code => $_rates) {
    foreach ($_rates as $_rate) {
        if ($_rate->getErrorMessage()) {
            $_error = $_rate->getErrorMessage();
        }
    }
}
if (!$_error && $this->getErrorsOnly()) {
    $_error = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('carriers/udsplit/specificerrmsg', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
}
?>

<?php if (\Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\Dropship\Helper\Data')->compareMageVer('1.4.1.0', '1.8.0.0')): ?>
<tr>
    <td colspan="<?php if (\Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Tax\Helper\Data')->displayCartBothPrices()) {echo '6';} else {echo '4';}?>">
<?php endif ?>


<div style="float:right">
    <?php echo __('Subtotal:')?>
    <strong><?php echo $_hlp->formatPrice($this->getSubtotal()) ?></strong>
</div>
<?php if (!$this->isVirtual()): ?>
<?php if ($this->getShowDropdowns()): ?>
<?php if ($_error): ?>
    <?php echo $this->escapeHtml($_error) ?>
<?php else: ?>
    <?php echo __('Select Shipping:')?>
    <select name="vendor_shipping_method[<?php echo $_a->getId() ?>][<?php echo $_v->getId()?>]" class="shipment-methods" style="width:auto">
    <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
        <?php if (!$useUdTitles):?>
            <optgroup label="<?php echo $this->getCarrierName($code) ?>">
        <?php endif ?>
        <?php foreach ($_rates as $_rate): ?>
        <?php if ($_rate->getErrorMessage()): ?>
            <?php //echo $_rate->getErrorMessage() ?>
        <?php else:
            $_price = $this->getShippingPrice($_rate->getPrice(), \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Tax\Helper\Data')->displayShippingPriceIncludingTax());
            $_incl = $this->getShippingPrice($_rate->getPrice(), true);
            if (\Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Tax\Helper\Data')->displayShippingBothPrices() && $_incl != $_price) {
                $_price .= ' ('.__('Incl. Tax ').$_incl.')';
            }
        ?>
            <option value="<?php echo $this->escapeHtml($_rate->getCode()) ?>" <?php if($_rate->getCode()===$this->getShippingMethod('code')) echo ' selected="selected"' ?>>
                <?php echo $_rate->getMethodTitle() ?> - <?php echo $_price ?>
            </option>
        <?php endif ?>
        <?php endforeach; ?>
        <?php if (!$useUdTitles):?>
            </optgroup>
        <?php endif ?>
    <?php endforeach; ?>
    </select>
<?php endif; ?>
<?php else: ?>
    <?php echo $this->getShippingMethod('carrier_title').' - '.$this->getShippingMethod('method_title') ?>
    (<strong><?php echo $this->getShippingPrice($this->getShippingMethod('price'), \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Tax\Helper\Data')->displayShippingPriceIncludingTax()) ?></strong>)
<?php endif; ?>
<?php endif; ?>

<?php if (\Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\Dropship\Helper\Data')->compareMageVer('1.4.1.0', '1.8.0.0')): ?>
</td></tr>
<?php endif ?>

<?php endswitch ?>