<?php
/** @var \Unirgy\Dropship\Helper\Data $_hlp */
$_hlp = \Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\Dropship\Helper\Data');
$_v = $this->getVendor();
$useUdTitles = $_hlp->getScopeFlag('carriers/udsplit/use_dropship_titles');
?>
<?php switch ($this->getPart()): case 'header': ?>

<tr class="udropship-cart-vendor-header">
    <td colspan="10" style="padding-top:5px; padding-bottom:0">
    <?php if ($_v->getId()): ?>
        <h3><?php echo $_v->getVendorName() ?> - <?php echo $_v->getFormatedAddress('text_small') ?></h3>
    <?php else: ?>
        <h3><?php echo __('Unknown vendor')?></h3>
    <?php endif ?>
    <?php $vendorErrors = $this->getQuote1()->getMinVendorOrderAmountErrors(); ?>
    <?php if (!empty($vendorErrors) && !empty($vendorErrors[$_v->getId()])): ?>
        <p class="item-msg error">* <?php echo $this->escapeHtml($vendorErrors[$_v->getId()]) ?></p>
    <?php endif ?>
    </td>
</tr>

<?php break; case 'footer':
$_shippingRateGroups = $this->getEstimateRates();
$_error = false;
foreach ($_shippingRateGroups as $code => $_rates) {
    foreach ($_rates as $_rate) {
        if ($_rate->getErrorMessage()) {
            $_error = $_rate->getErrorMessage();
        }
    }
}
if (!$_error && $this->getErrorsOnly()) {
    $_error = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('carriers/udsplit/specificerrmsg', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
}
?>

<tr class="udropship-cart-vendor-footer">
    <td colspan="10">
        <div class="udsplit-vendor-subtotal" style="float:right">
            <?php echo __('Subtotal:')?>
            <strong><?php echo $_hlp->formatPrice($this->getSubtotal()) ?></strong>
        </div>
        <?php if (!$this->isVirtual()): ?>
        <?php if ($this->getShowDropdowns()): ?>
        <?php if ($_error): ?>
            <?php echo $this->escapeHtml($_error) ?>
        <?php else: ?>
            <?php echo __('Select Shipping:')?>
            <input type="checkbox" name="shipping_method" checked="checked" style="display:none" disabled="disabled" />
            <select name="shipping_method[<?php echo $_v->getId()?>]" class="shipment-methods" style="width:auto">
            <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
                <?php if (!$useUdTitles):?>
                    <optgroup label="<?php echo $this->getCarrierName($code) ?>">
                <?php endif ?>
                <?php foreach ($_rates as $_rate): ?>
                <?php if ($_rate->getErrorMessage()): ?>
                    <?php //echo $_rate->getErrorMessage() ?>
                <?php else:
                    $_price = $this->getShippingPrice($_rate->getPrice(), \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Tax\Helper\Data')->displayShippingPriceIncludingTax());
                    $_incl = $this->getShippingPrice($_rate->getPrice(), true);
                    if (\Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Tax\Helper\Data')->displayShippingBothPrices() && $_incl != $_price) {
                        $_price .= ' ('.__('Incl. Tax ').$_incl.')';
                    }
                ?>
                    <option value="<?php echo $this->escapeHtml($_rate->getCode()) ?>" <?php if($_rate->getCode()===$this->getShippingMethod('code')) echo ' selected="selected"' ?>>
                        <?php echo $_rate->getMethodTitle() ?> - <?php echo $_price ?>
                    </option>
                <?php endif ?>
                <?php endforeach; ?>
                <?php if (!$useUdTitles):?>
                    </optgroup>
                <?php endif ?>
            <?php endforeach; ?>
            </select>
        <?php endif; ?>
        <?php else: ?>
            <?php echo $this->getShippingMethod('carrier_title').' - '.$this->getShippingMethod('method_title') ?>
            (<strong><?php echo $this->getShippingPrice($this->getShippingMethod('price'), \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Tax\Helper\Data')->displayShippingPriceIncludingTax()) ?></strong>)
        <?php endif; ?>
        <?php endif; ?>
    </td>
</tr>

<?php endswitch ?>
